AtlasOfLivingAustralia/ecodata

application.properties, grails-app/domain/au/org/ala/ecodata/Project.groovy, grails-app/services/au/org/ala/ecodata/ProjectService.groovy
Allowed end dates to be inferred from duration.
=> Added actual project duration.

grails-app/controllers/au/org/ala/ecodata/AdminController.groovy, grails-app/services/au/org/ala/ecodata/MetadataService.groovy
=> Run site updates in batches.

grails-app/controllers/au/org/ala/ecodata/AdminController.groovy, grails-app/services/au/org/ala/ecodata/MetadataService.groovy
Case insensitive exclusion of n/a from spatial portal.
=> Batching for centroid update.

application.properties, grails-app/conf/BootStrap.groovy, grails-app/conf/Config.groovy, grails-app/conf/UrlMappings.groovy, grails-app/controllers/au/org/ala/ecodata/ProjectController.groovy, grails-app/controllers/au/org/ala/ecodata/RecordController.groovy, grails-app/controllers/au/org/ala/ecodata/RecordImportController.groovy, grails-app/domain/au/org/ala/ecodata/Record.groovy, grails-app/services/au/org/ala/ecodata/RecordImportService.groovy, grails-app/services/au/org/ala/ecodata/RecordService.groovy
Securing Record CRUD operations and other updates for pigeonhole
=> Securing record CRUD operations

grails-app/services/au/org/ala/ecodata/RecordService.groovy
fix to use the correct image metadata update service & recordedBy
=>  image metadata update service & recordedBy

grails-app/controllers/au/org/ala/ecodata/PermissionsController.groovy
=> fixes #118: added service to retrieve all projects of a user

grails-app/controllers/au/org/ala/ecodata/PermissionsController.groovy, grails-app/domain/au/org/ala/ecodata/ProjectActivity.groovy, src/groovy/au/org/ala/ecodata/AccessLevel.groovy, test/integration/au/org/ala/ecodata/ProjectActivityControllerSpec.groovy
Relates to https://github.com/AtlasOfLivingAustralia/biocollect/pull/80 from biocollect.
=> Adds 'projectParticipant' access level, and allows ProjectActivities to be flagged as publicAccess

grails-app/controllers/au/org/ala/ecodata/ActivityController.groovy, grails-app/controllers/au/org/ala/ecodata/RecordController.groovy, grails-app/domain/au/org/ala/ecodata/Record.groovy, grails-app/services/au/org/ala/ecodata/ActivityService.groovy, models/faunaSurveyDetails/dataModel.json, models/floraSurveyDetails/dataModel.json, src/groovy/au/org/ala/ecodata/converter/ListConverter.groovy
Update to fauna and flora data model
Added ability to list activities and record by projects.
Included species name and guid.
=> Added ability to list activities and record by projects.

grails-app/conf/data/mapping.json
- ES: Added new filter to sort by dateCreated
=> #biocollect-584

grails-app/services/au/org/ala/ecodata/CommonService.groovy, grails-app/services/au/org/ala/ecodata/ProjectService.groovy, src/groovy/au/org/ala/ecodata/converter/SciStarterConverter.groovy
=> #biocollect-592

grails-app/controllers/au/org/ala/ecodata/SiteController.groovy, grails-app/services/au/org/ala/ecodata/SpatialService.groovy, grails-app/services/au/org/ala/ecodata/WebService.groovy, src/groovy/au/org/ala/ecodata/GeometryUtils.groovy
Added admin methods to update site geographic facets by siteId.
=> Changed spatial lookup to use WKT.

grails-app/conf/data/mapping.json, grails-app/services/au/org/ala/ecodata/CommonService.groovy, grails-app/services/au/org/ala/ecodata/ProjectService.groovy, grails-app/services/au/org/ala/ecodata/SensitiveSpeciesService.groovy, src/groovy/au/org/ala/ecodata/converter/SciStarterConverter.groovy, test/unit/au/org/ala/ecodata/SensitiveSpeciesServiceSpec.groovy
Reverts AtlasOfLivingAustralia/ecodata#286
=> Revert "Biocollect 559"

grails-app/services/au/org/ala/ecodata/ProjectService.groovy
- Prevent processing duplicate records coming from SciStarter
=> #biocollect-559

application.properties, grails-app/conf/BuildConfig.groovy
=> #biocollect-621

application.properties, grails-app/services/au/org/ala/ecodata/DownloadService.groovy, src/groovy/au/org/ala/ecodata/reporting/CSProjectXlsExporter.groovy
DWC records in download show event date (corrected to occurrence-local date), event time and event timestamp (uncorrected ISO 8601 date-time with timezone, so that people can nut out oddities)
Corrected field order in records.csv
=> More understandable date/time information in DwC data

src/groovy/au/org/ala/ecodata/converter/RecordConverter.groovy, src/groovy/au/org/ala/ecodata/converter/RecordFieldConverter.groovy, src/groovy/au/org/ala/ecodata/converter/SpeciesConverter.groovy
Fixing issues relating to conversion of outputs to records. 
**Main features**
* Use survey type to determine basis of record #580 
* Only create records if output has a valid species guid #583 
* Use survey licence as record licence #581 
* Map output scientificName to record scientificName #582
=> Fixing record creation

grails-app/controllers/au/org/ala/ecodata/ManagementUnitController.groovy, grails-app/services/au/org/ala/ecodata/ManagementUnitService.groovy, src/main/groovy/au/org/ala/ecodata/reporting/ManagementUnitXlsExporter.groovy, src/main/groovy/au/org/ala/ecodata/reporting/TabbedExporter.groovy, src/test/groovy/au/org/ala/ecodata/reporting/ManagementUnitXlsExporterSpec.groovy
@chrisala This is the back-end changes for the Management unit core services report.
=> commit change on the core services report content #2432

scripts/misc/reinstateDeletedSurveyData.js
AtlasOfLivingAustralia/biocollect#1394
=> reinstate deleted records from Water Quality Records survey

grails-app/init/au/org/ala/ecodata/BootStrap.groovy
Following https://github.com/AtlasOfLivingAustralia/biocollect/pull/1413 and other [similar PRs](https://github.com/search?q=is%3Apr+author%3Avjrj+org%3AAtlasOfLivingAustralia+ala-i18n+external&type=Issues), this PR allows the use of the ala-i18n package and crowdin packaged translations.
=> Usage of external ala-i18n resources

grails-app/services/au/org/ala/ecodata/ParatooService.groovy, src/main/groovy/au/org/ala/ecodata/DateUtil.groovy, src/main/groovy/au/org/ala/ecodata/converter/ListConverter.groovy, src/main/groovy/au/org/ala/ecodata/converter/RecordConverter.groovy, src/test/groovy/au/org/ala/ecodata/ParatooServiceSpec.groovy, src/test/groovy/au/org/ala/ecodata/SpeciesReMatchServiceSpec.groovy
- delete activity on re-import
- check if species record is present
-
=> update to Paratoo code

grails-app/controllers/au/org/ala/ecodata/AdminController.groovy, grails-app/services/au/org/ala/ecodata/ParatooService.groovy, src/main/groovy/au/org/ala/ecodata/converter/FeatureConverter.groovy, src/main/groovy/au/org/ala/ecodata/paratoo/ParatooProtocolConfig.groovy, src/test/groovy/au/org/ala/ecodata/ParatooServiceSpec.groovy, src/test/groovy/au/org/ala/ecodata/SiteServiceSpec.groovy, src/test/groovy/au/org/ala/ecodata/paratoo/ParatooProtocolConfigSpec.groovy
- fixes NPE when calculation convex hull
- new site for edited site
=> fauna plot

grails-app/domain/au/org/ala/ecodata/Hub.groovy, grails-app/services/au/org/ala/ecodata/HubService.groovy, grails-app/services/au/org/ala/ecodata/MetadataService.groovy, src/test/groovy/au/org/ala/ecodata/HubServiceSpec.groovy, src/test/groovy/au/org/ala/ecodata/MetadataServiceSpec.groovy
AtlasOfLivingAustralia/fieldcapture#3260
=> per hub facet intersection config

grails-app/conf/application.groovy, grails-app/conf/logback.xml, grails-app/controllers/au/org/ala/ecodata/AdminController.groovy, grails-app/controllers/au/org/ala/ecodata/MetadataController.groovy, grails-app/domain/au/org/ala/ecodata/ExternalId.groovy, grails-app/domain/au/org/ala/ecodata/Site.groovy, grails-app/services/au/org/ala/ecodata/ElasticSearchService.groovy, grails-app/services/au/org/ala/ecodata/HubService.groovy, grails-app/services/au/org/ala/ecodata/MetadataService.groovy, grails-app/services/au/org/ala/ecodata/ProjectService.groovy, grails-app/services/au/org/ala/ecodata/SiteService.groovy, grails-app/services/au/org/ala/ecodata/SpatialService.groovy, scripts/releases/5.0/updateMERITHubConfig.js, src/main/groovy/au/org/ala/ecodata/reporting/ProjectXlsExporter.groovy, src/test/groovy/au/org/ala/ecodata/ElasticSearchServiceSpec.groovy, src/test/groovy/au/org/ala/ecodata/MetadataServiceSpec.groovy, src/test/groovy/au/org/ala/ecodata/ProjectServiceSpec.groovy, src/test/groovy/au/org/ala/ecodata/SearchControllerSpec.groovy, src/test/groovy/au/org/ala/ecodata/SiteServiceSpec.groovy, src/test/groovy/au/org/ala/ecodata/SpatialServiceSpec.groovy, src/test/groovy/au/org/ala/ecodata/reporting/ProjectXlsExporterSpec.groovy
- updated boundary intersection logic
- calculates primary and other states and electorates
- intersection logic checks for project's hub to get layers
- bulk site intersection gets geographic layers for intersection from hub of project. Also added start date to query sites
- created hub specific geographic config for MERIT
=> update boundary intersection logic

grails-app/controllers/au/org/ala/ecodata/AdminController.groovy, grails-app/services/au/org/ala/ecodata/ActivityService.groovy, grails-app/services/au/org/ala/ecodata/ElasticSearchService.groovy, grails-app/services/au/org/ala/ecodata/OrganisationService.groovy, grails-app/services/au/org/ala/ecodata/SiteService.groovy, grails-app/services/au/org/ala/ecodata/SpatialService.groovy, src/main/groovy/au/org/ala/ecodata/GeometryUtils.groovy, src/test/groovy/au/org/ala/ecodata/GeometryUtilsSpec.groovy, src/test/groovy/au/org/ala/ecodata/SiteServiceSpec.groovy
- fixes pixelated/step shaped shapefiles
#999
- can index dependencies of a list of projects
=> issue with stepped shape file 

grails-app/controllers/au/org/ala/ecodata/ParatooController.groovy, grails-app/controllers/au/org/ala/ecodata/UrlMappings.groovy, grails-app/domain/au/org/ala/ecodata/Activity.groovy, grails-app/services/au/org/ala/ecodata/ParatooService.groovy, scripts/releases/5.0/updateMissingActivityExternalIds.js, scripts/utils/audit.js, src/test/groovy/au/org/ala/ecodata/ParatooServiceSpec.groovy
- gets list of collection ids of a user
- fixed issue with externalIds not saving on Activity entity
- added script to update external ids on saved activities
=> #1007 org method get all collections; requires database update

grails-app/controllers/au/org/ala/ecodata/ApiKeyInterceptor.groovy, grails-app/controllers/au/org/ala/ecodata/ParatooController.groovy
- re-enable swagger ui
- refactored definition
=> #1007 re-enable swagger ui

grails-app/services/au/org/ala/ecodata/SpatialService.groovy
- fix invalid geometry
- use wkt endpoint to get shape of pid
- fix bug with caching pid geojson object
=> fix invalid geometry AtlasOfLivingAustralia/fieldcapture#3292

grails-app/conf/application.groovy, grails-app/controllers/au/org/ala/ecodata/ProjectController.groovy, grails-app/jobs/au/org/ala/ecodata/ImportSciStarterJob.groovy, grails-app/services/au/org/ala/ecodata/ElasticSearchService.groovy, grails-app/services/au/org/ala/ecodata/ProjectService.groovy, grails-app/services/au/org/ala/ecodata/SiteService.groovy, src/main/groovy/au/org/ala/ecodata/converter/SciStarterConverter.groovy, src/test/groovy/au/org/ala/ecodata/ProjectControllerSpec.groovy, src/test/groovy/au/org/ala/ecodata/converter/SciStarterConverterSpec.groovy
- Reworked import process to use the new SciStarter API
- Updated project area indexing to retrieve valid geoJSON & simplify if necessary
=> SciStarter Updates

grails-app/services/au/org/ala/ecodata/SpatialService.groovy
- more geometry fixes
- fixed null pointer exception
- fixed issue with searching for an object by name and subsequent caching of null value
=> more geometry fixes and others - AtlasOfLivingAustralia/fieldcapture#3292

grails-app/services/au/org/ala/ecodata/SpatialService.groovy
=> fixed type cast exception AtlasOfLivingAustralia/fieldcapture#3292

grails-app/controllers/au/org/ala/ecodata/AdminController.groovy, grails-app/services/au/org/ala/ecodata/SpatialService.groovy
- update sites of a list of projects
- retry convex hull if first attempt throws exception
=> update sites of a list of projects AtlasOfLivingAustralia/fieldcapture#3292

grails-app/conf/application.groovy, grails-app/controllers/au/org/ala/ecodata/ProjectController.groovy, grails-app/controllers/au/org/ala/ecodata/SpatialController.groovy, grails-app/controllers/au/org/ala/ecodata/UrlMappings.groovy, grails-app/domain/au/org/ala/ecodata/GeographicInfo.groovy, grails-app/services/au/org/ala/ecodata/ProjectService.groovy, grails-app/services/au/org/ala/ecodata/SpatialService.groovy, scripts/releases/5.1/updateSiteLocationMetadata.js, src/main/groovy/au/org/ala/ecodata/reporting/ProjectXlsExporter.groovy, src/test/groovy/au/org/ala/ecodata/ProjectServiceSpec.groovy, src/test/groovy/au/org/ala/ecodata/SearchControllerSpec.groovy, src/test/groovy/au/org/ala/ecodata/SpatialServiceSpec.groovy, src/test/groovy/au/org/ala/ecodata/reporting/ProjectXlsExporterSpec.groovy
- manual project geographic information ui support
- spatial object name standardisation
=> manual project geographic information ui support AtlasOfLivingAustralia/fieldcapture#1724

grails-app/conf/application.groovy, grails-app/controllers/au/org/ala/ecodata/SpatialController.groovy, grails-app/domain/au/org/ala/ecodata/GeographicInfo.groovy, grails-app/services/au/org/ala/ecodata/SpatialService.groovy, scripts/releases/5.1/updateSiteLocationMetadata.js
- added intersectWith to find states of an electorate
- added statewide field
- updated script to standardise project geographicInfo fields
=> AtlasOfLivingAustralia/fieldcapture#1724 & #1034

grails-app/services/au/org/ala/ecodata/SiteService.groovy
- fixed an issue where EMSA sites were filtered out
=>  AtlasOfLivingAustralia/ecodata#3430

grails-app/init/au/org/ala/ecodata/BootStrap.groovy, grails-app/services/au/org/ala/ecodata/SpatialService.groovy
- pre-fetch electorates and states intersection so that it is available instantly
=> #1076 - apply 5% intersection rule to objects that intersect

grails-app/controllers/au/org/ala/ecodata/HarvestController.groovy
https://github.com/AtlasOfLivingAustralia/biocollect/issues/1682
=> commit darwin core api update #1085

src/main/groovy/au/org/ala/ecodata/reporting/ProjectXlsExporter.groovy
- added delivered approved and total to RLP and RDP exports
=> #1081- added delivered approved and total to RLP and RDP exports

grails-app/conf/application.groovy, grails-app/controllers/au/org/ala/ecodata/HarvestController.groovy, grails-app/jobs/au/org/ala/ecodata/DarwinCoreArchiveJob.groovy, grails-app/services/au/org/ala/ecodata/ActivityService.groovy, grails-app/services/au/org/ala/ecodata/ProjectService.groovy, grails-app/services/au/org/ala/ecodata/RecordService.groovy, src/test/groovy/au/org/ala/ecodata/ProjectServiceSpec.groovy
- added feature to save darwin core archive to disk and periodically update it
- added feature to serve darwin core archive from disk or on demand
=> #1683  added feature to save darwin core archive to disk and periodically update it

src/main/groovy/au/org/ala/ecodata/DateUtil.groovy, src/main/groovy/au/org/ala/ecodata/paratoo/ParatooCollectionId.groovy, src/test/groovy/au/org/ala/ecodata/DateUtilSpec.groovy
- parse date with and without milliseconds
=> #1103 parse date with and without milliseconds

grails-app/conf/application.groovy
Please hold off on this one @salomon-j I'm going to add a script to update the MERIT hub config (which also includes a reference to the electorate layer)
=> Updated electoral layer #3534

grails-app/services/au/org/ala/ecodata/ElasticSearchService.groovy, src/test/groovy/au/org/ala/ecodata/ElasticSearchServiceSpec.groovy
- add survey date to index when date cannot be found from species occurrence records
=> AtlasOfLivingAustralia/biocollect#1676 - add survey date to index when date cannot be found from species occurrence records

grails-app/services/au/org/ala/ecodata/ElasticSearchService.groovy
- add capability to find publicly accessible surveys/projects
=> #1775 add capability to find publicly accessible surveys/projects
